#include "asd"

uniform float my_uniform_val = 1.0++;

struct a {};

void a(int a, int b, float c) {
  int a = 1;
  val a = 1;
  while (1 < 3) {}
  do {
  } while(12);
  if (a == 1) {
  } else {
  }

  switch (1 < 2) {
    case 1:
      do_thing(1);
      break;
    case 2:
      do_other_thing(-2.E-1);
      return;
  }
  sampler2D a;
  return 1;
}

const int a = ++1++;
const int A = a = b += trunc();
vec3(c, 2, b);
a a = 1;
a();

int[3][4] myfunc(int a, float b) {
a.b.c;}
